# webserver
server:
  port: 8080
  context-path: /

# template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jmx:
    enabled: false
upms:
  url: http://221.178.232.93:86/oss-upms
  interceptor.patterns: /**/*.do,/

dc:
  sc:
#在upms里面配置的项目编号
    p-code: hello-upms
#本地upms项目访问地址
    upms-url: http://221.178.232.93:86/oss-upms
#apiKey
    api-key: 543df6e9aed348dc85e05593b1c9c24d
  cas:
#本地应用项目访问地址
    local-app-url: http://127.0.0.1:8080/hello-upms
#本地sso(cas)项目访问地址
    cas-server-url: http://221.178.232.93:86/oss-sso